### ISSUE TITLE
No requirements.txt

### ISSUE THREAD

**Issue by RammusLeo** [xljh0520/JOTR#2]
Hi! Thanks for your great work. I'm interested in this project and I'm trying to reproduce it, but I guess the environment configuration file is not provided? Would you mind checking your environment settings and updating it?

**Comment by xljh0520** [comment]
Thanks for your attention. I update a requirements.sh, and you can prepare the environment through it.

**Comment by RammusLeo** [comment]
Thank you for quick reply! The evaluation results match the table on the paper well.
