### ISSUE TITLE
NCCL Timeout Error when applying NCE Loss

### ISSUE THREAD

**Issue by RammusLeo** [xljh0520/JOTR#4]
Hi! Sorry to bother you again. In my further experiments I want to explore the potential of contrastive learning. But I encounter an error when setting `with_contrastive=True`: 
``` bash
[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might
run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=66, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1801979 milliseconds b$
fore timing out.
[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might 
run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.                                                       
terminate called after throwing an instance of 'std::runtime_error'                                                                                         
  what():  [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=67, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1802085 milliseconds b$
fore timing out.                                                                                                                                            
```
I try to debug the problem, and I find the issue probably comes from line 236-241 in `common/model.py` where the **allgather operation** executing.
``` python
if self.cfg.with_contrastive:
      dense_feat = allgather(dense_feat) # B, C, D, H, W
      reduced_orig_joint_img = allgather(reduced_orig_joint_img.div(32).sub(1)) # (-1, 1), B, 15, 3
      joint_img_cur = allgather(joint_img[layer_idx].mul(2).sub(1)) # (-1, 1) B, 15, 3
      joint_valid_cur = allgather(reduced_orig_joint_trunc) # B, 15, 1
      is_3D_mask = allgather(meta_info['is_3D']) 
      is_3D_mask = is_3D_mask.flatten() == 1 # B,
```
When the program goes to here, it turns out no response and then occurs timeout error. It looks like a DDP operation error but I am not so familiar with it, so I am looking for help if you have any solutions to debug. Thanks very much!

**Comment by xljh0520** [comment]
Can you provide more information? For example, what GPU are you using, which distribution of the operating system, PyTorch version, CUDA version, and so on.

In addition to NCCL, you can also try using gloo. More information can be found [here](https://pytorch.org/docs/stable/distributed.html?highlight=distributed#module-torch.distributed).

**Comment by RammusLeo** [comment]
OK, here's my settings:

> GPU: Nvidia RTX 3090
Operating System: Ubuntu 18.04 x86_64
Python Version: 3.7
Pytorch Version: 1.12.1+cu113
CUDA Version: 11.4
NCCL Version: 2.10.3

and here's the command to start train:
``` bash
CUDA_VISIBLE_DEVICES=6,7 \
python -m torch.distributed.launch \
--master_port 29521 \
--nproc_per_node 2 \
train.py \
--cfg ./assets/yaml/fine_tune.yml \
--distributed \
--lr 5e-5 \
--lr_backbone 5e-5 \
--weight_decay 0.0001 \
--exp_id "fine_tune" \
--resume_ckpt output/JOTR/checkpoint/snapshot_18.pth.tar \
--continue
```
It looks like `gloo` is for CPU communication. Except this issue, the NCCL connection for DDP operation seems work well. It looks like `gloo` is for CPU communication. So I want to figure out whether there are any problems in my settings or code under GPU settings. Thanks for your help!

**Comment by xljh0520** [comment]
I haven't tested it on a 3090 and Ubuntu machine. My environment is CentOS and V100/A100 and runs well. I have written a unit test that you can try in your environment.

```
import torch
import torch.distributed as dist
class AllGather(torch.autograd.Function):
    """An autograd function that performs allgather on a tensor."""

    @staticmethod
    def forward(ctx, tensor):
        output = [torch.empty_like(tensor) for _ in range(dist.get_world_size())]
        torch.distributed.all_gather(output, tensor)
        ctx.rank = dist.get_rank()
        ctx.batch_size = tensor.shape[0]
        return torch.cat(output, dim=0)

    @staticmethod
    def backward(ctx, grad_output):
        return (
            grad_output[ctx.batch_size * ctx.rank : ctx.batch_size * (ctx.rank + 1)],
            None,
        )
allgather = AllGather.apply

if __name__ == '__main__':
    # init process group
    dist.init_process_group(backend='gloo')
    torch.cuda.set_device(dist.get_rank())
    print('rank:', dist.get_rank(), 'world_size:', dist.get_world_size())
    x = torch.randn(32, 3, 256, 256, requires_grad=True).cuda()
    y = allgather(x)
    print('rank:', dist.get_rank(), 'y:', y.shape)
```

Running scripts
```
torchrun --nproc_per_node 2 test_allgather.py
```

**Comment by RammusLeo** [comment]
Thanks very much for your scripts! I'm sorry for late reply. After I deeply research for the reason of error, I found that it is the incompleteness of my dataset cause this error. I have set `collect_fn` parameter in `dataloader` in order to deal with the missing data, but this will cause a stuck when conducting the allgather operation. As shown in pytorch manual, this error can be visable by `export TORCH_DISTRIBUTED_DEBUG=DETAIL`. 
[Reference in discuss.pytorch.org](https://discuss.pytorch.org/t/all-gather-get-stuck-when-data-samples-are-not-the-same-length/156848)
``` bash
RuntimeError: Detected mismatch between collectives on ranks. Rank 0 is running inconsistent collective: CollectiveFingerPrint(OpType=ALLGATHER, TensorShape
=[41, 256, 8, 8, 8], TensorDtypes=Float, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cuda, layout=Strided (default), requires_grad=false (
default), pinned_memory=false (default), memory_format=(nullopt))
RuntimeError: Detected mismatch between collectives on ranks. Rank 1 is running inconsistent collective: CollectiveFingerPrint(OpType=ALLGATHER, TensorShape
=[40, 256, 8, 8, 8], TensorDtypes=Float, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cuda, layout=Strided (default), requires_grad=false (
default), pinned_memory=false (default), memory_format=(nullopt))
```
To solve this problem, I think one way is to complement the data, or set an `try: ... expection: ...` to handle the error. So I'd like to share with you about this detail and express my apologies for bothering you about this.
However, even I have dealt with this problem, it goes to `CUDA Memory Error`. I set `train_batch_size=4` and use 2 GPUs for about 24G memory each, but it still goes memory error. Thus I want to know how much the memory costs in your experiments approximately? Or how can I reduce my computation costs by adjusting the hyperparameters in NCE Loss? 
Thanks again for you considerating reply.

**Comment by xljh0520** [comment]
I run my code with `train_batch_size=16` with 8 V100 or `train_batch_size=32` with 4 A100. However, based on my experience, a 24GB graphics memory should be sufficient to run experiments with a batch size of 4, there may be other issues as well.

**Comment by RammusLeo** [comment]
OK I got it! I'll try to figure out the issue. Thank you so much!
