### ISSUE TITLE
RuntimeError: All tensors must be on devices[0]: 0

### ISSUE THREAD

**Issue by 124518** [xljh0520/JOTR#9]
Hello, I encountered an error during the reproduction process. Could you help me?
![image](https://github.com/xljh0520/JOTR/assets/100846916/afeecb00-59f0-4c5b-98c7-44aaba710f47)

**Comment by xljh0520** [comment]
It seems like there is an issue with multi-GPU distributed training here. May I ask how many GPUs you are using? Could you provide the command you are running?
